#!/bin/bash

# WARNING: Please, DO NOT edit this file! It is maintained in the Repository Template (https://github.com/nhs-england-tools/repository-template). Raise a PR instead.

set -euo pipefail

# Pre-commit git hook to check the EditorConfig rules compliance over changed
# files. It ensures all non-binary files across the codebase are formatted
# according to the style defined in the `.editorconfig` file. This is a
# editorconfig command wrapper. It will run editorconfig natively if it is
# installed, otherwise it will run it in a Docker container.
#
# Usage:
#   $ [options] ./check-file-format.sh
#
# Options:
#   check={all,staged-changes,working-tree-changes,branch}  # Check mode, default is 'working-tree-changes'
#   dry_run=true                                            # Do not check, run dry run only, default is 'false'
#   BRANCH_NAME=other-branch-than-main                      # Branch to compare with, default is `origin/main`
#   FORCE_USE_DOCKER=true                                   # If set to true the command is run in a Docker container, default is 'false'
#   VERBOSE=true                                            # Show all the executed commands, default is `false`
#
# Exit codes:
#   0 - All files are formatted correctly
#   1 - Files are not formatted correctly
#
# The `check` parameter controls which files are checked, so you can
# limit the scope of the check according to what is appropriate at the
# point the check is being applied.
#
#   check=all: check all files in the repository
#   check=staged-changes: check only files staged for commit.
#   check=working-tree-changes: check modified, unstaged files. This is the default.
#   check=branch: check for all changes since branching from $BRANCH_NAME
#
# Notes:
#   Please make sure to enable EditorConfig linting in your IDE. For the
#   Visual Studio Code editor it is `editorconfig.editorconfig` that is already
#   specified in the `./.vscode/extensions.json` file.

# ==============================================================================

function main() {
  if [[ ${#@} != 0 ]] && declare -f "run-editorconfig$1" >/dev/null 2>&1 ; then
    "run-editorconfig$1" "${@:2}"
  else
    main-invocation "$@"
  fi
}

function main-invocation() {

  cd "$(git rev-parse --show-toplevel)"

  # shellcheck disable=SC2154
  is-arg-true "${dry_run:-false}" && dry_run_opt="--dry-run"

  check=${check:-working-tree-changes}
  if ! declare -f "list-files-to-check--$check" >/dev/null 2>&1 ; then
    echo "Unrecognised check mode: $check" >&2 && exit 1
  fi

  if command -v editorconfig > /dev/null 2>&1 && ! is-arg-true "${FORCE_USE_DOCKER:-false}"; then
    method=--natively
  else
    method=--via-docker
  fi

  list-files-to-check--"$check" |
  # Maximum size of command line and environment combined is typically
  # 2MB on Linux but only 256KB on macOS. Assume a maximum filename
  # length of 200 characters and limiting us to batches of 1000 files
  # gives us a bit of a safety margin.
  dry_run_opt="${dry_run_opt:-}" xargs -0 --max-args=1000 --no-run-if-empty scripts/githooks/check-file-format.sh "$method"
}

# Run editorconfig natively.
# Arguments (provided as environment variables):
#   dry_run_opt=[dry run option]
# Arguments (provided as positional parameters): files to check
function run-editorconfig--natively() {

  # shellcheck disable=SC2046,SC2086
  editorconfig \
    --exclude '.git/' $dry_run_opt "$@"
}

# Run editorconfig in a Docker container.
# Arguments (provided as environment variables):
#   dry_run_opt=[dry run option]
# Arguments (provided as positional parameters): files to check
function run-editorconfig--via-docker() {

  # shellcheck disable=SC1091
  source ./scripts/docker/docker.lib.sh

  # shellcheck disable=SC2155
  local image=$(name=mstruebing/editorconfig-checker docker-get-image-version-and-pull)
  docker run --rm --platform linux/amd64 \
    --volume "$PWD":/check \
    "$image" \
      sh -c "ec --exclude '.git/' $dry_run_opt $(printf '%q ' "$@")"
}

# ==============================================================================

# These all produce filenames terminated by a NUL character, so that we
# can handle filenames that contain spaces.

function list-files-to-check--all() {
  git ls-files -z
}

function list-files-to-check--staged-changes() {
  git diff -z --diff-filter=ACMRT --name-only --cached
}

function list-files-to-check--working-tree-changes() {
  git diff -z --diff-filter=ACMRT --name-only
}

function list-files-to-check--branch() {
  git diff -z --diff-filter=ACMRT --name-only ${BRANCH_NAME:-origin/main}
}

# ==============================================================================

function is-arg-true() {

  if [[ "$1" =~ ^(true|yes|y|on|1|TRUE|YES|Y|ON)$ ]]; then
    return 0
  else
    return 1
  fi
}

# ==============================================================================

is-arg-true "${VERBOSE:-false}" && set -x

main "$@"

exit 0
